const mockTestData = [
  {
    studentId: "463",
    name: "변재은",
    gender: "female",
    educationalGroup: "동구",
    school: "남목고",
    monthlyTests: {
      "2025-04": {
        totalScore: 680,
        tests: [
          { name: "제자리멀리뛰기", record: "241", score: "97" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "15.02", score: "100" },
          { name: "메디신볼", record: "8.6", score: "95" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "31.2", score: "99" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "134.5", score: "94" },
          { name: "10M왕복", record: "8.87", score: "96" },
          { name: "20M왕복", record: "15.51", score: "99" },
        ],
      },
      "2025-03": {
        totalScore: 680,
        tests: [
          { name: "제자리멀리뛰기", record: "250", score: "100" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "15.14", score: "100" },
          { name: "메디신볼", record: "9", score: "96" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "29.6", score: "97" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "122.5", score: "92" },
          { name: "10M왕복", record: "8.92", score: "95" },
          { name: "20M왕복", record: "15.39", score: "100" },
        ],
      },
      "2025-02": {
        totalScore: 664,
        tests: [
          { name: "제자리멀리뛰기", record: "238", score: "96" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "14.95", score: "100" },
          { name: "메디신볼", record: "9", score: "96" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "27.7", score: "95" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "98.5", score: "87" },
          { name: "10M왕복", record: "9.12", score: "93" },
          { name: "20M왕복", record: "15.75", score: "97" },
        ],
      },
    },
  },
  {
    studentId: "39",
    name: "이현서",
    gender: "male",
    educationalGroup: "동구",
    school: "남목고",
    monthlyTests: {
      "2025-04": {
        totalScore: "649",
        tests: [
          { name: "제자리멀리뛰기", record: "275", score: "91" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "14.08", score: "99" },
          { name: "메디신볼", record: "10.8", score: "96" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "21.1", score: "91" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "172.5", score: "90" },
          { name: "10M왕복", record: "8.34", score: "91" },
          { name: "20M왕복", record: "14.87", score: "91" },
        ],
      },
      "2025-03": {
        totalScore: "654",
        tests: [
          { name: "제자리멀리뛰기", record: "281", score: "93" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "13.98", score: "100" },
          { name: "메디신볼", record: "10.4", score: "94" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "20.2", score: "90" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "177.5", score: "91" },
          { name: "10M왕복", record: "8.38", score: "91" },
          { name: "20M왕복", record: "14.49", score: "95" },
        ],
      },
      "2025-02": {
        totalScore: "613",
        tests: [
          { name: "제자리멀리뛰기", record: "270", score: "90" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "14.63", score: "93" },
          { name: "메디신볼", record: "8.6", score: "88" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "11.7", score: "81" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "129.5", score: "81" },
          { name: "10M왕복", record: "8.48", score: "90" },
          { name: "20M왕복", record: "14.92", score: "90" },
        ],
      },
    },
  },
  {
    studentId: "1295",
    name: "박은서",
    gender: "female",
    educationalGroup: "남구",
    school: "문현고",
    monthlyTests: {
      "2025-04": {
        totalScore: "680",
        tests: [
          { name: "제자리멀리뛰기", record: "238", score: "96" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "14.91", score: "100" },
          { name: "메디신볼", record: "10.1", score: "100" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "24.5", score: "92" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "140", score: "96" },
          { name: "10M왕복", record: "8.81", score: "96" },
          { name: "20M왕복", record: "15.2", score: "100" },
        ],
      },
      "2025-03": {
        totalScore: "678",
        tests: [
          { name: "제자리멀리뛰기", record: "244", score: "98" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "15.04", score: "100" },
          { name: "메디신볼", record: "9.9", score: "99" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "24.8", score: "92" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "130", score: "94" },
          { name: "10M왕복", record: "8.94", score: "95" },
          { name: "20M왕복", record: "15.2", score: "100" },
        ],
      },
    },
  },
  {
    studentId: "127",
    name: "이장혁",
    gender: "male",
    educationalGroup: "남구",
    school: "언양고",
    monthlyTests: {
      "2025-04": {
        totalScore: "677",
        tests: [
          { name: "제자리멀리뛰기", record: "302", score: "100" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "13.8", score: "100" },
          { name: "메디신볼", record: "10.8", score: "96" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "33", score: "100" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "177", score: "91" },
          { name: "10M왕복", record: "8.28", score: "92" },
          { name: "20M왕복", record: "14.14", score: "98" },
        ],
      },
    },
  },
  {
    studentId: "231",
    name: "정준혁",
    gender: "male",
    educationalGroup: "남구",
    school: "문수고",
    monthlyTests: {
      "2025-04": {
        totalScore: "674",
        tests: [
          { name: "제자리멀리뛰기", record: "298", score: "99" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "13.99", score: "100" },
          { name: "메디신볼", record: "11.6", score: "98" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "27.6", score: "97" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "174", score: "90" },
          { name: "10M왕복", record: "8.46", score: "90" },
          { name: "20M왕복", record: "13.85", score: "100" },
        ],
      },
    },
  },
  {
    studentId: "95",
    name: "고민혁",
    gender: "male",
    educationalGroup: "남구",
    school: "대현고",
    monthlyTests: {
      "2025-04": {
        totalScore: "672",
        tests: [
          { name: "제자리멀리뛰기", record: "282", score: "94" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "13.82", score: "100" },
          { name: "메디신볼", record: "10.2", score: "94" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "32.5", score: "100" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "209.5", score: "97" },
          { name: "10M왕복", record: "8.59", score: "89" },
          { name: "20M왕복", record: "14.16", score: "98" },
        ],
      },
    },
  },
  {
    studentId: "625",
    name: "백지훈",
    gender: "male",
    educationalGroup: "북구",
    school: "무룡고",
    monthlyTests: {
      "2025-04": {
        totalScore: "642",
        tests: [
          { name: "제자리멀리뛰기", record: "262", score: "87" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "14.21", score: "97" },
          { name: "메디신볼", record: "10.9", score: "96" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "31.7", score: "100" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "148", score: "85" },
          { name: "10M왕복", record: "8.78", score: "87" },
          { name: "20M왕복", record: "15", score: "90" },
        ],
      },
    },
  },
  {
    studentId: "383",
    name: "김나연",
    gender: "female",
    educationalGroup: "중구",
    school: "학성여고",
    monthlyTests: {
      "2025-04": {
        totalScore: "663",
        tests: [
          { name: "제자리멀리뛰기", record: "230", score: "93" },
          { name: "윗몸일으키기", record: "0", score: "0" },
          { name: "Z-런달리기", record: "15.66", score: "97" },
          { name: "메디신볼", record: "9.6", score: "98" },
          { name: "100M달리기", record: "0", score: "0" },
          { name: "유연성(좌전굴)", record: "26.7", score: "94" },
          { name: "던지기", record: "0", score: "0" },
          { name: "배근력", record: "140.5", score: "96" },
          { name: "10M왕복", record: "9.34", score: "91" },
          { name: "20M왕복", record: "16.07", score: "94" },
        ],
      },
    },
  },
  {
    studentId: "151",
    name: "신석윤",
    gender: "male",
    educationalGroup: "동구",
    school: "대성고",
    monthlyTests: {},
  },
  {
    studentId: "471",
    name: "정채현",
    gender: "female",
    educationalGroup: "동구",
    school: "대송고",
    monthlyTests: {},
  },
  {
    studentId: "663",
    name: "윤지성",
    gender: "male",
    educationalGroup: "동구",
    school: "남목고",
    monthlyTests: {},
  },
  {
    studentId: "791",
    name: "김다은",
    gender: "female",
    educationalGroup: "동구",
    school: "남목고",
    monthlyTests: {},
  },
  {
    studentId: "135",
    name: "이태훈",
    gender: "male",
    educationalGroup: "중구",
    school: "성신고",
    monthlyTests: {},
  },
  {
    studentId: "1159",
    name: "이승준",
    gender: "male",
    educationalGroup: "남구",
    school: "대현고",
    monthlyTests: {},
  },
  {
    studentId: "175",
    name: "이장빈",
    gender: "male",
    educationalGroup: "중구",
    school: "울산고",
    monthlyTests: {},
  },
  {
    studentId: "183",
    name: "이연제",
    gender: "male",
    educationalGroup: "중구",
    school: "성신고",
    monthlyTests: {},
  },
  {
    studentId: "1143",
    name: "이지유",
    gender: "female",
    educationalGroup: "남구",
    school: "범서고",
    monthlyTests: {},
  },
];

export default mockTestData;
